server.port=8888

# --- Gateway routes ---
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Explicit routes (Utilisent le Load Balancer Eureka)
spring.cloud.gateway.routes[0].id=users-service
spring.cloud.gateway.routes[0].uri=lb://users-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**,/api/auth/**

spring.cloud.gateway.routes[1].id=events-service
spring.cloud.gateway.routes[1].uri=lb://events-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/events/**

spring.cloud.gateway.routes[2].id=ms-reservation
spring.cloud.gateway.routes[2].uri=lb://ms-reservation
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/reservations/**

spring.cloud.gateway.routes[3].id=ms-tickets
spring.cloud.gateway.routes[3].uri=lb://ms-tickets
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/tickets/**

spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://notification-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/notifications,/api/notifications/**

# --- Swagger aggregation ---
springdoc.swagger-ui.urls[0].name=Service UTILISATEURS
springdoc.swagger-ui.urls[1].name=Service EVENEMENTS
springdoc.swagger-ui.urls[2].name=Service RESERVATIONS
springdoc.swagger-ui.urls[3].name=Service TICKETS
springdoc.swagger-ui.urls[0].url=/api/users/v3/api-docs
springdoc.swagger-ui.urls[1].url=/api/events/v3/api-docs
springdoc.swagger-ui.urls[2].url=/api/reservations/v3/api-docs
springdoc.swagger-ui.urls[3].url=/api/tickets/v3/api-docs