# discovery-server configuration
server.port=8761

# Utilise EUREKA_HOSTNAME (ex: discovery-server) dans Docker, sinon localhost
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false