server.port=8091
springdoc.api-docs.path=/api/feedback/v3/api-docs

# --- Database ---
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/db_feedback
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
