server.port=8089
springdoc.api-docs.path=/api/reservations/v3/api-docs

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/reservation_event
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update