server.port=8089

springdoc.api-docs.path=/api/reservations/v3/api-docs

# --- Database ---
spring.datasource.url=jdbc:postgresql://localhost:5432/reservation_event
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=create
logging.level.root=INFO
