
server.port=9000

notification.mongo.uri=mongodb://${MONGO_HOST:localhost}:27017/notifications_db

notification.rabbitmq.url=amqp://${RABBITMQ_USER:guest}:${RABBITMQ_PASSWORD:guest}@${RABBITMQ_HOST:localhost}:${RABBITMQ_PORT:5672}
notification.rabbitmq.exchange=user.events
notification.rabbitmq.exchange-type=topic
notification.rabbitmq.queue=notification.user.events
notification.rabbitmq.routing-key=user.#
notification.rabbitmq.prefetch=10
notification.rabbitmq.reconnect-delay-ms=5000

notification.max-history=100


notification.eureka.enabled=true
notification.eureka.app-name=notification-service
notification.eureka.instance-host=${NOTIFICATION_INSTANCE_HOST:localhost}
notification.eureka.instance-ip=${NOTIFICATION_INSTANCE_IP:127.0.0.1}
