server.port=7890

# --- Database ---
spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Keycloak admin client ---
keycloak.auth-server-url=http://localhost:8180
keycloak.realm=microservices-realm
keycloak.client-id=users-service
keycloak.client-secret=ePja0P3sYA0dC12g11pCQ3FHPLQik6Oo
keycloak.admin.username=badisjl
keycloak.admin.password=12345

spring.cloud.compatibility-verifier.enabled=false
